//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidTracker.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocResources_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocResources_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CovidTracker.Localization.LocResources.fr", typeof(LocResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        internal static string HealthReportButton {
            get {
                return ResourceManager.GetString("HealthReportButton", resourceCulture);
            }
        }
        
        internal static string HealthReportTitle {
            get {
                return ResourceManager.GetString("HealthReportTitle", resourceCulture);
            }
        }
        
        internal static string RiskQueryButton {
            get {
                return ResourceManager.GetString("RiskQueryButton", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string SendReportButton {
            get {
                return ResourceManager.GetString("SendReportButton", resourceCulture);
            }
        }
        
        internal static string ReportSentTitle {
            get {
                return ResourceManager.GetString("ReportSentTitle", resourceCulture);
            }
        }
        
        internal static string ReportSentBody {
            get {
                return ResourceManager.GetString("ReportSentBody", resourceCulture);
            }
        }
        
        internal static string ReportNotSentTitle {
            get {
                return ResourceManager.GetString("ReportNotSentTitle", resourceCulture);
            }
        }
        
        internal static string ReportNotSentBody {
            get {
                return ResourceManager.GetString("ReportNotSentBody", resourceCulture);
            }
        }
        
        internal static string RiskLevelTitle {
            get {
                return ResourceManager.GetString("RiskLevelTitle", resourceCulture);
            }
        }
        
        internal static string RiskLevelBody {
            get {
                return ResourceManager.GetString("RiskLevelBody", resourceCulture);
            }
        }
        
        internal static string tested_positive {
            get {
                return ResourceManager.GetString("tested_positive", resourceCulture);
            }
        }
        
        internal static string fever {
            get {
                return ResourceManager.GetString("fever", resourceCulture);
            }
        }
        
        internal static string tiredeness {
            get {
                return ResourceManager.GetString("tiredeness", resourceCulture);
            }
        }
        
        internal static string dry_cough {
            get {
                return ResourceManager.GetString("dry_cough", resourceCulture);
            }
        }
        
        internal static string aches_and_pains {
            get {
                return ResourceManager.GetString("aches_and_pains", resourceCulture);
            }
        }
        
        internal static string nasal_congestion {
            get {
                return ResourceManager.GetString("nasal_congestion", resourceCulture);
            }
        }
        
        internal static string runny_nose {
            get {
                return ResourceManager.GetString("runny_nose", resourceCulture);
            }
        }
        
        internal static string sore_throat {
            get {
                return ResourceManager.GetString("sore_throat", resourceCulture);
            }
        }
        
        internal static string diarrhea {
            get {
                return ResourceManager.GetString("diarrhea", resourceCulture);
            }
        }
    }
}
